version: "3"

services:
  redis:
    image: redis:latest
    command: sh -c "redis-server"
    ports:
      - "6379:6379"

  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis